### ISSUE TITLE
Confirmation screen is shown for success even i did not registered username

### ISSUE THREAD

**Issue by asemiankevich** [status-im/ens-usernames#12]
I see the confirmation screen in the following cases:

1. when i want to register name and tap `register with transaction` it is shown at the background for a second before blue transaction screen is loaded

2. when transaction to register the name is failed

3. when i close transaction screen

Also the domain is shown as registered when it is actually free https://github.com/status-im/ens-usernames/issues/10

So actually it is shown right when i tap the `register with transaction` no matter of the txn outcome

![image](https://user-images.githubusercontent.com/28752642/45480200-1eb1c180-b751-11e8-8fac-e4a788ead557.png)

**Comment by bgits** [comment]
This is an optimistic update as the would be delay from the time the user signs the transaction to it being confirmed. Perhaps some UX idea's here.

**Comment by denis-sharypin** [comment]
@asemiankevich @bgits 

> 1.when I want to register name and tap register with the transaction it is shown at the background for a second before blue transaction screen is loaded

This screen should not be visible at this moment

> 2. when transaction to register the name is failed

That's tricky. It's not a success screen of getting your domain. Can we know that transaction is failed and show Status of it here @bgits ?


> 3. when i close transaction screen

If user closes transaction screen she should get back to the screen where a transaction was initiated. I assume in this case it is 
<img width="233" alt="screenshot 2018-09-14 16 43 48" src="https://user-images.githubusercontent.com/6559881/45557217-63b32200-b83d-11e8-91e6-a4f1a7c15b88.png">

**Comment by bgits** [comment]
Regarding point 1. the confirmation window is triggered by the status wallet or some other wallet like metamask, at this point we don't know if it's signed and submitted or not signed. This requires some research to determine if this particular state can be determined in web3.

The short way we check for a failure triggers false positives, such as a transaction not mined after 50 seconds would be a failure, I think there are more robust solutions we can experiment with such as polling or subscribing to events may not be battery friendly on mobile.

If the user submits a transaction to register why would it show them that the domain is available? I would think this is the time to show the confirmation screen?

**Comment by bgits** [comment]
updated in PR: https://github.com/status-im/ens-usernames/pull/64/files
