### ISSUE TITLE
Migrate project to foundry template

### ISSUE THREAD

**Issue by 0x-r4bbit** [status-im/ens-usernames#129]
This is so that we have an easier time maintaining this codebase.
There were a few changes we already had to make in this legacy codebase. The tooling is outdated and not maintained anymore.

Part of this issue is:

- [ ] Using our foundry template instead (https://github.com/vacp2p/foundry-template)
- [ ] Migrate all tests to foundry tests
- [ ] Upgrade the solidity version due to incompatibility in foundry
- [ ] Ideally, make use of custom errors instead of string messages

**Comment by 0x-r4bbit** [comment]
@3esmit can we please put up a PR that shows the progress on this issue?

**Comment by 3esmit** [comment]
Closed by #130
