### ISSUE TITLE
Back / Forward buttons are disabled in Status browser when using ENS username dapp

### ISSUE THREAD

**Issue by asemiankevich** [status-im/ens-usernames#13]
back / forward buttons are disabled in browser so i need to use `refresh` all the time to search for new name or whatever. 

![image](https://user-images.githubusercontent.com/28752642/45480334-72240f80-b751-11e8-8bd0-3eed591791d0.png)

![image](https://user-images.githubusercontent.com/28752642/45480423-a13a8100-b751-11e8-8838-586422802b33.png)

**Comment by bgits** [comment]
In order to be able to use the navigation buttons we need to add url based routing to the DApp.

**Comment by bgits** [comment]
Should be fixed by this issue: https://github.com/status-im/ens-usernames/issues/14

**Comment by rachelhamlin** [comment]
@bgits is this something you can work on or better @lpissinali?
