### ISSUE TITLE
"Release name" option available for name held < 1 year

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/ens-usernames#15]
A user owning a name for < 1 year should not have the option to release the name. 

![image](https://user-images.githubusercontent.com/15470435/45509981-df0aca00-b790-11e8-80a8-b862264d47ad.png)

**Comment by bgits** [comment]
removed in this commit https://github.com/status-im/ens-usernames/pull/32/commits/675204731644a09377608d6567c2fa429df54925
