### ISSUE TITLE
Contact code request happens on page load

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/ens-usernames#17]
The contact code should only be requested when the user has tapped the contact code field, while registering a name.

![image](https://user-images.githubusercontent.com/15470435/45510246-8f78ce00-b791-11e8-871f-c39f9f70bc48.png)

**Comment by bgits** [comment]
So the contact code field will be empty until it's touched?

**Comment by rachelhamlin** [comment]
Yes, permission should be granted in context and on a per-ID basis. With
the new EIP1102 pattern, we'll need to add a trigger for the wallet, too.

**Comment by bgits** [comment]
My thinking was that we ask for permission once upon the dapp loading then we can use the code throughout the dapp. Otherwise ask each each time the dapp needs access to the contact code?

I don't believe the the wallet address is uses the EIP yet?

**Comment by rachelhamlin** [comment]
Ask each time the DApp needs access - it should be optional for each name registered by the user.

**Comment by rachelhamlin** [comment]
🙌
