### ISSUE TITLE
Register the DApp on ENS

### ISSUE THREAD

**Issue by jeluard** [status-im/ens-usernames#18]
To be included in status the DApp must be available via an ENS name. This way updates will be picked up seamlessly. The name should use `eth` domain.

Status will follow this EIP to map to an IPFS hash: https://ethereum-magicians.org/t/eip-1062-formalize-ipfs-hash-into-ens-ethereum-name-service-resolver/281

**Comment by bgits** [comment]
As far as I know we don't own statusnames.eth.

The highest bid for `statusnames.eth` was from this account: https://etherscan.io/address/0x5b655eda7d101f98934392cc3610bcb25b633789

Here is the transaction: https://etherscan.io/tx/0x302c3c1862249f317967671cd825b6e1cef3fd1eab5ecddd574969db7e39fc37

**Comment by bgits** [comment]
Since we have `names.stateofus.eth` is this considered done?
