### ISSUE TITLE
Add date of registration to taken names

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/ens-usernames#28]
When I search for a name that is already registered, I should see the date that it was registered.

*Expected*
![image](https://user-images.githubusercontent.com/15470435/46204428-8b19ec80-c31d-11e8-90af-b3bbac34a1cd.png)

*Current*
![image](https://user-images.githubusercontent.com/15470435/46204802-bfda7380-c31e-11e8-822d-23ef42aefb03.png)

**Comment by bgits** [comment]
You want the date registered or the date it can be released?

**Comment by bgits** [comment]
Added date of registration in this commit: https://github.com/status-im/ens-usernames/pull/32/commits/b4f3d09010796554e86f6be4085b6aca84258a4e

**Comment by rachelhamlin** [comment]
Yes date of registration 👍🏼

**Comment by bgits** [comment]
Ok, it's in the PR.  The one issue is it will only be available on names that were registered using the most recent registry, for it to be available on names registered when stateofus.eth was owned by another registry the username has to moved to the new registry and we don't expose that method in our UI.

**Comment by bgits** [comment]
If we transfer stateofus.eth to another registry contract that we deploy in the future, all names registered on the original contract will be impacted. On launch, having only one contract ever for registrations on mainnet will have no impact.

**Comment by rachelhamlin** [comment]
Makes sense. Will keep mental note of that.
