### ISSUE TITLE
Search doesn't work from the results screen

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/ens-usernames#31]
In version https://ipfs.infura.io/ipfs/QmU9hq7mR1ApLf6S37E9BTiziQRPu1xCnjUg2TzZ7poBo6/ of the DApp, the search bar has been added to the top of each results screen. 👍🏼

Unfortunately, it doesn't work. When I type something new into the search bar, the UI reflects it directly in the results card.

As I deleted characters from my initial search, this happened...
<img src="https://user-images.githubusercontent.com/15470435/46207682-83ac1080-c328-11e8-8475-84d524f1f01c.png" width=200/><img src="https://user-images.githubusercontent.com/15470435/46207693-8b6bb500-c328-11e8-86b9-34956a7cbb8b.png" width=200/><img src="https://user-images.githubusercontent.com/15470435/46207702-91619600-c328-11e8-837f-3c75590eea85.png" width=200/>

When I type in a new search, the UI should not change. When I hit enter, I should get new search results.

**Comment by bgits** [comment]
Pushed a fix to this branch: https://github.com/status-im/ens-usernames/pull/21
