### ISSUE TITLE
Fix formatting of T&C screen; add agreement 

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/ens-usernames#39]
The bullets on the T&C screen require more spacing.

The contract addresses at the bottom do not fit the screen.

There should be a fixed bottom bar with an `Agree to all terms` box, which is required for the user to `Send SNT`. 

*Expected*
<img src="https://user-images.githubusercontent.com/15470435/46589191-11000b00-ca75-11e8-9885-1496d65eb583.png" width=250/>

*Current*
<img src="https://user-images.githubusercontent.com/15470435/46589208-4e649880-ca75-11e8-8a19-e1dd04c0f974.png" width=250>

**Comment by asemiankevich** [comment]
fixed
