### ISSUE TITLE
Remove Edit button on owned name screen

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/ens-usernames#44]
For v1, we'll drop the manage/edit username flow.

This means that when I look up a name that I own, I should not see the `Edit` button at the bottom.

![image](https://user-images.githubusercontent.com/15470435/46680206-8d4e3780-cbb6-11e8-8121-a6e270326664.png)

**Comment by rachelhamlin** [comment]
Can you remove this @bgits?

**Comment by bgits** [comment]
This PR, removes the button: https://github.com/status-im/ens-usernames/pull/59
