### ISSUE TITLE
Error screen when I haven't actually searched

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/ens-usernames#45]
When I start a search, don't type anything at all, and then close the keyboard (because I changed my mind about searching), I am shown the error "Names are made with letters and numbers only." 

If a user hasn't typed anything, the screen should remain blank.

*Expected*
<img src="https://user-images.githubusercontent.com/15470435/46685149-becd0000-cbc2-11e8-933c-4bbc5f0a6c3e.png" width=250/>

*Actual*
<img src="https://user-images.githubusercontent.com/15470435/46685138-b83e8880-cbc2-11e8-976d-f96ee96798c9.png" width=250/>

**Comment by asemiankevich** [comment]
seems to be fixed in https://cloudflare-ipfs.com/ipfs/QmSJXVfcxU1sTpTsSTidUaFgFfu9DzusaSJSBwE6BzFcxr/
