### ISSUE TITLE
Wallet code is editable when editing contact code for the domain i already own

### ISSUE THREAD

**Issue by asemiankevich** [status-im/ens-usernames#5]
I own a domain.
I search for this domain.
I tap `Edit contact code`
At the same time wallet code is editable

![image](https://user-images.githubusercontent.com/28752642/45427253-0d13df80-b6a7-11e8-8310-7fe6fafd975b.png)

**Comment by bgits** [comment]
This is a feature, users should be able to change the addresses associated with a domain name.

**Comment by bgits** [comment]
maybe make it 'Edit Addresses'?

**Comment by asemiankevich** [comment]
@denis-sharypin  ? :)

**Comment by rachelhamlin** [comment]
@bgits can we disable this for now? When wallet address is optional from registration we can change it.

**Comment by rachelhamlin** [comment]
Replaced with #25
