### ISSUE TITLE
Registration date is missing when checking booked domain

### ISSUE THREAD

**Issue by asemiankevich** [status-im/ens-usernames#51]
Registration date should be shown if i browse the already booked domain

![image](https://user-images.githubusercontent.com/28752642/46741310-6f173300-ccad-11e8-9e2f-59b1464b9119.png)

**Comment by rachelhamlin** [comment]
I believe this is the same as this issue - https://github.com/status-im/ens-usernames/issues/28

**Comment by asemiankevich** [comment]
fixed
