### ISSUE TITLE
Confirmation screen is not shown after i register domain

### ISSUE THREAD

**Issue by asemiankevich** [status-im/ens-usernames#53]
When i complete the txn to pay for domain i should be redirected to the confirmation screen. 
NOTE: it is shown for a while right after i click `Register with transaction`. 

Expected screen:

![image](https://user-images.githubusercontent.com/28752642/46744852-a1785e80-ccb4-11e8-8ba8-f0499514a91a.png)

Instead i am returned to the main page:
![image](https://user-images.githubusercontent.com/28752642/46744798-8dccf800-ccb4-11e8-89b3-90762d5d4dfd.png)

**Comment by bgits** [comment]
Fixed in this pr: https://github.com/status-im/ens-usernames/pull/54
