### ISSUE TITLE
Resolution issue with `carl`

### ISSUE THREAD

**Issue by chadyj** [status-im/ens-usernames#75]
By now everyone has heard the story of trying to chat with `carl` and getting a random Chinese dude!  There was much laughs at the thought of a squatter.

But after digging deeper it looks like that Carl registered his name but for the contact code wasn't captured.

<img width="320" alt="screen shot 2018-10-26 at 5 53 49 pm" src="https://user-images.githubusercontent.com/116099/47577835-25367a00-d948-11e8-912e-cf37f7bc6be7.png">

So we have these potential issues:

1. Contact code potentially not saved (Carl thought he did, but isn't 100% certain)

2. `carl` resolves to `0x04ee8c9662467fbce7398d5d9591a5b3657ba6f487bdfc33dd6d053d6252b36ba09b9d9cba387ab267e607807709195135fca1ccb8a81a6931ee67079975f9091c`, but it shouldn't resolve at all since there isn't a contact code saved (see screenshot above or search for `carl` in the dapp)

Can we verify #1 and also fix the issue when we resolve incorrectly?

cc @rachelhamlin @3esmit @bgits @yenda @naghdy

**Comment by chadyj** [comment]
oh and one more thing....

3. How can Carl edit his ENS name and update the contact code?

**Comment by oskarth** [comment]
1. No management API yet, so can’t edit contact code in UI.
2. contact code not granted, so resolved to 0 pub key, this should be validated in UI
3. UX around grant code a bit so so, many people missed this

**Comment by 3esmit** [comment]
Issue is caused in status-react when resolving pubkey x = 0 and y = 0.
When both are 0, it should not continue, perhaps show an error message

**Comment by yenda** [comment]
@3esmit actually this is not the problem, the problem is that the chinese guy registered `c` (https://etherscan.io/enslookup?q=c.stateofus.eth) so that name was resolved and since `carl` doesn't resolve to a valid address, the resolution of `c` to the public-key of the chinese guy was staying in the app state. I fixed the input so that now resolution of a shorter username is discarded as soon as you add additional characters in this PR https://github.com/status-im/status-react/pull/6537

**Comment by chadyj** [comment]
Closed in https://github.com/status-im/status-react/pull/6537#event-1930824087

**Comment by rachelhamlin** [comment]
Still having this issue on desktop, when I enter `carl` or `bruce`, for example. It should be fixed in the desktop builds right @yenda?

**Comment by yenda** [comment]
`carl` doesn't resolve for me either because it isn't associated with public-key, but `bruce` does

**Comment by rachelhamlin** [comment]
`bruce` is also working for me this morning 🤷🏼‍♀️
