### ISSUE TITLE
Show error screen when special characters used in search

### ISSUE THREAD

**Issue by Serhy** [status-im/ens-usernames#9]
Most of the special chars are not allowed to be searched for supposed ENS name. However some them are.
We need to validate 'Search' input field (on all screens where we display it) allowing only letters and numbers be allowed as ENS value.  

To reproduce:
1) Navigate to latest END Dapp prototype in testnet (https://ipfs.infura.io/ipfs/QmYLj7gYZfKPee4BirNPBug5z41UbYf699Gy78K9M1x4pi/)
2) Search for a `•••...’€€€`. 
**Expected result:**  `Names are made with letters and numbers only` screen keep stay
**Actual result:** `•••...’€€€.statuofus.eth` available
3) Now staying on this screen edit ENS name to `-/:;()$&@.,?!’()status`
**Expected result:**  Redirect to `Names are made with letters and numbers only` screen 
**Actual result:** `-/:;()$&@.,?!’()status` available for registration
4) Hit 'Register with transaction' button
**Actual result:** Endless spinner appears.

<img width="305" alt="screen shot 2018-09-12 at 17 31 57" src="https://user-images.githubusercontent.com/8749671/45432121-be1f7780-b6b1-11e8-99ff-500824674a94.png">

**Comment by alwx** [comment]
Fixed already.
