### ISSUE TITLE
ENS 'Terms of name registration' wrong parameter formats showing '[object Object]'

### ISSUE THREAD

**Issue by jinhojang6** [status-im/ens-usernames#94]
i18n formatting problems

![1](https://user-images.githubusercontent.com/41753422/52914637-35ff6700-330e-11e9-8060-33bb5159dcf7.png)

Some parameters like 'stateofus', 'eth_address' show '[object Object]' errors.

.json files containing the information [information](https://github.com/status-im/ens-usernames/blob/8d4d00396ec9b1df71eb57bdcf1e0d9734aa456f/app/languages/en.json)

terms.js containing the related [information](https://github.com/status-im/ens-usernames/blob/master/app/components/ens/terms.js)

**Comment by rachelhamlin** [comment]
Thanks @jinhojang93!

**Comment by rachelhamlin** [comment]
When fixing this, we also need to fix the second bullet copy:

`2. n non-alphanumeric characters;`

to

`2. contain non-alphanumeric characters;`
