### ISSUE TITLE
[iOS] 'Send transaction' screen shows up automatically

### ISSUE THREAD

**Issue by jinhojang93** [status-im/ens-usernames#96]
On the iOS app, at the 'Terms of name registration' step, the 'Send transaction' screen shows up automatically which should be shown up when clicking on 'Send SNT' at the bottom.

There is no problem with Android devices.

**Comment by rachelhamlin** [comment]
This one is now on the browser team's Pivotal board.

**Comment by jinhojang93** [comment]
Thanks. Where can I take a look at the Pivotal board?

**Comment by rachelhamlin** [comment]
Here it is @jinhojang93: https://www.pivotaltracker.com/projects/2231918

**Comment by flexsurfer** [comment]
i have the same behaviour on Android
